image: continuumio/miniconda3:latest

before_script:
  - apt-get install build-essential
  - conda env create -f gitlab-ci-env3.yml
  - source activate bornagain3

tests:
  stage: test
  script:
    - pwd
    - uname -a
    - echo $PATH
    - cd developer
    - ./compile-fortran.sh
    - cd ../test
    - pytest --ignore=test_simulate_clcore.py --ignore=test_simulate_cromer_mann.py  --ignore=test_mplviews.py
