image: "ubuntu:20.04"

before_script:
  - export DEBIAN_FRONTEND=noninteractive

stages:
  - build
  - test
  - doc
  - deploy

build:
  stage: build
  script:
  - source ubuntu_setup.sh

test:
  stage: test
  dependencies:
  - build
  script:
  - cd test
  - pytest

doc:
  stage: doc
  dependencies:
  - build
  script:
  - cd doc
  - bash update_docs.sh

pages:
  stage: deploy
  dependencies:
  - doc
  only:
  - master
  script:
  - cd doc
  - cp -r build/html ../public
  artifacts:
    paths:
    - public
