image: ubuntu:latest

before_script:
  - bash ubuntu-setup.sh

tests:
  stage: test
  script:
  - cd test
  - pytest

pages:
  script:
  - cd doc
  - bash update-documentation.sh
  - cp -r build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
