# This image has the dependencies of reborn pre-installed.  It was created with developer/docker/build_docker.sh
image: registry.gitlab.com/kirianlab/reborn/ubuntu-20.04:latest

before_script:
  - export reborn=$(pwd)
  - export PATH=/usr/local/miniconda/bin:$PATH # Set up in developer/docker/build_docker.sh
  - export PYTHONPATH=$reborn # Put reborn git repo in the python path
  - cd $reborn/developer
  - bash test_minimal_dependencies.sh
  - bash cleanup_everything.sh
  - source activate reborn # This was set up in developer/docker/build_docker.sh
#  - conda list # Helpful for debugging in the future...
#  - python --version
#  - cat /usr/local/miniconda/envs/reborn/etc/OpenCL/vendors/pocl.icd
#  - bash check_pyopencl.sh # Check that opencl works
#  - bash build_inplace.sh # Compile fortran code
#  - cd $reborn
#  - python -c 'from reborn import fortran' # Check fortran compilation

tests:
  stage: test
  script:
  - cd $reborn/test
  - pytest -v

doc:
  script:
  - cd $reborn/doc
  - bash update_docs.sh
  except:
  - master

pages:
  script:
  - cd $reborn/doc
  - bash update_docs.sh
  - cp -r build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
