#image: continuumio/miniconda3:latest # This image doesn't seem to have make or gfortran
image: ubuntu:latest # This image doesn't work with GPU stuff
#image: nvidia:opencl # Can't seem to use this one... needs password?

before_script:
  - uname -a
  - basepath=$(pwd)
  - echo $basepath
  - apt-get -qq -y update
  - apt-get -qq -y apt-utils
  - apt-get -qq -y install wget
  - apt-get -qq -y install gfortran
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $basepath/miniconda.sh
  - bash $basepath/miniconda.sh -b -p $basepath/miniconda
  - export PATH=$basepath/miniconda/bin:$PATH
  - conda update -n base -c defaults conda
  - conda env create -f gitlab-ci-env.yml
  - source activate bornagain
  - cd $basepath/developer
  - ./compile-fortran.sh

tests:
  stage: test
  script:
  - allow_failure: true
  - cd $basepath/test
  - pytest --ignore=test_simulations.py --ignore=test_clcore.py --ignore=test_clcore_interpolations.py --ignore=test_simulate_clcore.py --ignore=test_simulate_cromer_mann.py

pages:
  script:
  - allow_failure: true
  - cd $basepath/doc
  - ./update-documentation.sh
  - cd $basepath
  - mkdir public
  - cp -r $basepath/doc/html/* $basepath/public
  artifacts:
    paths:
    - public
  only:
  - master
