image: ubuntu:20.04

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - source ubuntu-setup.sh

tests:
  stage: test
  script:
  - cd test
  - pytest -v test_math.py
  - pytest -v test_clcore_interpolations.py
  - pytest -v

doc:
  script:
  - cd doc
  - bash update_docs.sh
  except:
  - master

pages:
  script:
  - cd doc
  - bash update_docs.sh
  - cp -r build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
