image: ubuntu:latest

before_script:
  - gitbasepath=$(pwd)
  - apt-get -qq -y update
  - apt-get -qq -y install apt-utils wget curl gfortran
  - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh --output $gitbasepath/miniconda.sh
  - bash $gitbasepath/miniconda.sh -b -p $gitbasepath/miniconda
  - export PATH=$gitbasepath/miniconda/bin:$PATH
  - conda update -n base -c defaults conda
  - conda env create -f bornagain-env.yml # gitlab-ci-env.yml
  - source activate bornagain
  - python setup.py develop

tests:
  stage: test
  script:
  - cd $gitbasepath/test
  - pytest

docs:
  script:
  - cd $gitbasepath/doc
  - ./update-documentation.sh
  - cp -r $gitbasepath/doc/html $gitbasepath/public
  artifacts:
    paths:
    - public
  only:
  - master
