#image: continuumio/miniconda3:latest # This image doesn't seem to have make or gfortran
#image: ubuntu:latest # This image doesn't work with GPU stuff
image: nvidia:opencl

before_script:
  - uname -a
  - basepath=$(pwd)
  - echo $basepath
  - apt-get -qq -y update
  - apt-get -qq -y apt-utils
  - apt-get -qq -y install wget
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $basepath/miniconda.sh
  - bash $basepath/miniconda.sh -b -p $basepath/miniconda
  - export PATH=$basepath/miniconda/bin:$PATH

tests:
  stage: test
  script:
  - conda env create -f bornagain3-env.yml # gitlab-ci-env3.yml
  - source activate bornagain3
  - cd test
  - pytest #--ignore=test_simulations.py --ignore=test_clcore.py --ignore=test_clcore_interpolations.py --ignore=test_simulate_clcore.py --ignore=test_simulate_cromer_mann.py  --ignore=test_mplviews.py --ignore=test_interpolations.py

pages:
  script:
  - conda env create -f bornagain3-env.yml # gitlab-ci-env3.yml
  - source activate bornagain3
  - cd doc
  - ./update-documentation.sh
  - cd ..
  - mkdir public
  - cp -r doc/html/* public
  artifacts:
    paths:
    - public
  only:
  - master
