image: "ubuntu:20.04"

before_script:
  - export DEBIAN_FRONTEND=noninteractive

stages:
  - build
  - test
  - doc
  - deploy

build:
  stage: build
  script:
  - source ubuntu_setup.sh
  artifacts:
    paths:
    - reborn.egg-info

test:
  stage: test
  script:
  - cd test
  - pytest

doc:
  stage: doc
  script:
    - cd doc
    - bash update_docs.sh

pages:
  stage: deploy
  script:
  - cp -r build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
