image: ubuntu:20.04

before_script:
  - source ubuntu-setup.sh

tests:
  stage: test
  script:
  - cd test
  - pytest

pages:
  script:
  - cd doc
  - bash update_docs.sh
  - cp -r build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
