#image: ubuntu:20.04
#image: rkirian/reborn:v01
image: registry.gitlab.com/kirianlab/reborn/ubuntu:latest

before_script:
#  - export DEBIAN_FRONTEND=noninteractive
#  - source ubuntu-setup.sh
  - ls /usr/local/miniconda/etc/OpenCL/vendors
  - export PATH=/usr/local/miniconda/bin:$PATH
  - export PYTHONPATH=$(pwd)
  - cd developer
  - bash compile_fortran.sh
  - cd ..

tests:
  stage: test
  script:
  - cd test
  - pytest -v test_math.py
  - python -c 'from pyopencl import array as clarray'
  - python -c 'from reborn.simulate.clcore import ClCore'
  - python -c 'from pyopencl import array as clarray; cl_array = clarray.Array'
  - python -c 'from reborn.simulate.clcore import help; help()'
  - pytest -v test_clcore_interpolations.py
  - pytest -v

doc:
  script:
  - cd doc
  - bash update_docs.sh
  except:
  - master

pages:
  script:
  - cd doc
  - bash update_docs.sh
  - cp -r build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
