image: continuumio/miniconda3:latest # Annoyingly, this image doesn't seem to have make or gfortran

before_script:
  - uname -a
  - pwd

tests:
  stage: test
  script:
  - pwd
  - uname -a
  - echo $PATH
  - conda env create -f gitlab-ci-env3.yml
  - source activate bornagain3
  - cd test
  - pytest --ignore=test_simulations.py --ignore=test_clcore.py --ignore=test_clcore_interpolations.py --ignore=test_simulate_clcore.py --ignore=test_simulate_cromer_mann.py  --ignore=test_mplviews.py --ignore=test_interpolations.py

pages:
  script:
  - conda env create -f gitlab-ci-env3.yml
  - source activate bornagain3
  - cd doc
  - ./update-documentation.sh
  - cd ..
  - mkdir public
  - cp -r doc/html/* public
  artifacts:
    paths:
    - public
  only:
  - master
