image: "ubuntu:20.04"

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - cd developer
  - ./cleanup_everything.sh
  - cd ..
  - source ubuntu_setup.sh

stages:
  - test
  - doc
  - deploy

test:
  stage: test
  script:
  - cd test
  - pytest

doc:
  stage: doc
  script:
    - cd doc
    - bash update_docs.sh
  cache:
    paths:
    - build

pages:
  stage: deploy
  only:
    - master
  script:
  - cd doc
  - cp -r build/html ../public
  artifacts:
    paths:
    - public
