image: ubuntu:latest

before_script:
  - source developer/ubuntu-setup.sh
#  - apt-get -qq -y update
#  - apt-get -qq -y install apt-utils wget curl gfortran libgl1-mesa-glx
#  - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh --output miniconda.sh
#  - bash miniconda.sh -b -p miniconda
#  - export PATH=./miniconda/bin:$PATH
#  - conda update -n base -c defaults conda
#  - conda env create -f bornagain-env.yml
#  - source activate bornagain
#  - python setup.py develop

tests:
  stage: test
  script:
  - cd test
  - pytest

pages:
  script:
  - cd doc
  - ./update-documentation.sh
  - cp -r html ../public
  artifacts:
    paths:
    - public
  only:
  - master
