name: reborn
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - scipy               # Installing scipy will install the minimal dependencies (numpy, etc.)
  - h5py                # Only if loading data using tools in reborn.external
  - matplotlib          # Only if you use the GUIs in reborn.viewers.mplviews
  - numba               # A few functions run faster with this
  - pyopencl            # Only if you are running GPU simulations
  - pytest              # Only if you are running unit tests
  - pyqt=5              # Only if you want to use the Qt GUIs (reborn.viewers.qtviews)
  - pyqtgraph           # Only if you want to use the Qt GUIs (reborn.viewers.qtviews)
  - pyopengl            # Only if you need 3D graphics
  - xraylib             # Only if you need scattering factors
  - joblib              # Only if you need parallelized pipelines
  - pandas              # Only if you need tabular data displays
  - sphinx              # Only if you are building docs
  - memory_profiler     # Only if you are building docs
  - fortran-compiler    # Only if you do not already have gfortran installed
  - ocl-icd-system      # Only if you installed pyopencl and do not manage ICDs manually
  - pip                 # Only if you are building docs
#  - pocl               # Possibly helpful to run unit tests without a GPU
#  - ocl_icd_wrapper_apple  # Possibly helpful for GPU simulations on Apple computers
#  - make               # Only if you are building docs on Apple or Windows computers
  - pip:                # Some packages only install via pip...
    - sphinx_rtd_theme  # Only if you are building docs
    - sphinx-gallery    # Only if you are building docs
    - pyvirtualdisplay  # Only if you are building docs
