name: reborn
channels:
  - conda-forge
dependencies:
  - python
  - scipy               # Installing scipy will install the minimal dependencies
  - h5py                # Only if loading data using tools in reborn.external
  - matplotlib          # Only if you use the GUIs in reborn.viewers.mplviews
  - numba               # A few functions run faster with this
  - pyopencl            # Only if you are running GPU simulations
  - pytest              # Only if you are running unit tests
  - pyqt=5              # Only if you want to use the Qt GUIs (reborn.viewers.qtviews)
  - pyqtgraph           # Only if you want to use the Qt GUIs (reborn.viewers.qtviews)
  - pyopengl            # Only if you need 3D graphics
  - xraylib             # Only if you need scattering factors
  - joblib              # For simple multiprocessing and pipelines
  - pandas              # For tabular data displays
#  - pocl               # Possibly helpful if pyopencl doesn't work
#  - ocl-icd-system     # Possibly helpful if pyopencl doesn't work
#  - fortran-compiler   # Possibly helpful for strange computers (windows, mac)
#  - make               # Possibly helpful for strange computers (windows, mac)
  - sphinx              # Only if you are building docs
  - memory_profiler     # Only if you are building docs
  - pip                 # Only if you are building docs
  - pip:
    - sphinx_rtd_theme  # Only if you are building docs
    - sphinx-gallery    # Only if you are building docs
    - pyvirtualdisplay  # Only if you are building docs
