name: reborn
channels:
  - conda-forge
dependencies:
  - python=3
  - future
  - scipy
  - h5py
  - matplotlib
  - numba
  - pyopencl
  - pocl
  - sphinx
  - pytest
  - pyqt=5
  - pyqtgraph
  - pyopengl
  - xraylib
  - pillow
  - memory_profiler
  - fortran-compiler
  - make
  - pip
  - pip:
    - cfelpyutils
    - sphinx_rtd_theme
    - sphinx-gallery
