name: reborn
channels:
  - conda-forge
dependencies:
  - python
#  - future
  - scipy
  - h5py
  - matplotlib
  - numba
  - pyopencl
#  - pocl
#  - ocl-icd-system
  - sphinx
  - pytest
  - pyqt=5
  - pyqtgraph
  - pyopengl
  - xraylib
  - pillow
  - memory_profiler
#  - fortran-compiler
#  - ipython
#  - make
  - pip
  - pip:
    - cfelpyutils
    - sphinx_rtd_theme
    - sphinx-gallery
