name: bornagain
channels:
  - conda-forge
dependencies:
  - python=3.6   # or 2.7
  - pyqt=5       # or 4
  - numpy
  - scipy
  - h5py
  - matplotlib
  - pyqtgraph
  - pyopencl
  - future
  - sphinx
  - pytest
  - pip:
    - cfelpyutils