name: bornagain
channels:
  - conda-forge
dependencies:
  - python=3.8
  - scipy
  - h5py
  - future
  - numba
  - pyopencl
  - sphinx
  - pytest
  - matplotlib
  - pyqt=5
  - pocl
  - pyqtgraph
#  - pyopengl
  - pip
  - make
  - pip:
    - cfelpyutils
    - sphinx_rtd_theme
