#!/bin/bash


if [ "$1" = "remake" ]; then 
	make html
	cp -r build/html/* html
	exit
fi

# Remove files auto-generated by sphinx-apidoc.  How can we get sphinx to stop dumping generated rst 
# files into the source directory?
rm source/bornagain.*rst
# Note that sphinx-apidoc exclude patterns need an absolute path.  This program sucks.
[ "$1" = "noapi" ] || sphinx-apidoc -o source -e -M ../bornagain ../bornagain/scatter*
make clean
make html
rm -r html
rm source/bornagain*.rst # modules.rst
mv build/html .
perl -p -i -e 's{<head>\n}{<head>\n  <meta name="robots" content="noindex, nofollow" />\n}' html/*.html

